from distutils.core import setup

setup(
    name='py_apsrtable',
    version='0.1',
    author='John Beieler',
    author_email='john.b30@gmail.com',
    packages=['py_apsrtable'],
    url='http://pypi.python.org/pypi/py_apsrtable/',
    license='LICENSE.txt',
    description='Provides functions to convert statistical results to LaTeX tables',
    long_description = """
    py_apsrtable is a Python package that aims to provide an easy method for
    turning statistical results generated by Python statistical packages, such
    as statsmodels, into formatted LaTeX tables. 

    More information can be found on `Github <http://johnb30.github.com/py_apsrtable/>`__.
    """
)
